#!/bin/sh

command="$1"
shift

case "$command" in
	add)
		for map in "$@"; do
			../alti-server/altx-tool -p maps/$map.altx plus/$map
			git add								\
				editor/maps/$map					\
				plus/$map							\
				editor_screenshots/${map}_collapsed.png	\
				maps/$map.altx
		done

		git commit -am "Add $*"
		;;
	delete|rm)
		for map in "$@"; do
			git rm -r								\
				editor/maps/$map					\
				plus/$map							\
				editor_screenshots/${map}_collapsed.png	\
				maps/$map.altx
		done

		git commit -am "Remove $*"
		;;
	finish)
		for map in "$@"; do
			../alti-server/altx-tool -p maps/$map.altx plus/$map
			git add -A editor/maps/$map
		done
		git commit -am "Update $*"
		;;
	*)
		echo "Syntax: $0 <add|delete|finish> <map>"
		exit 1
		;;
esac

git push

