#!/usr/bin/perl

my($size, $layer);
my($x, $y);

if(defined($ARGV[0]) && $ARGV[0]>=2 && $ARGV[0]<=2048 && $ARGV[0]%2==0) {
	$size=$ARGV[0];
} else {
	$size=512;
}

if(defined($ARGV[1]) && $ARGV[1]=~m/^\d$/) {
	$layer=$ARGV[1];
} else {
	$layer='\d';
}

while(<>) {
	if(m/<geometry /) {
		if(m/ layer="$layer" x="(\d+)" y="(\d+)" /) {
			$x=$1 % $size;
			$y=$2 % $size;
		} else {
			$x=undef;
			$y=undef;
		}
	}

	if(m/<translate / && defined($x) && defined($y)) {
		s/ x="[\d.-]+" / x="-$x.0" /;
		s/ y="[\d.-]+" / y="-$y.0" /;
	}

	print;
}

